name: Build CR6606 Final
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      TZ: Asia/Shanghai

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 安装环境
        run: sudo apt update && sudo apt install build-essential libncurses-dev bison flex libssl-dev python3 -y

      - name: 拉取源码 (Gitee 国内镜像)
        run: git clone https://gitee.com/immortalwrt/immortalwrt.git --depth=1 openwrt

      - name: 添加插件 (国内镜像，无墙)
        run: |
          cd openwrt/package
          git clone https://gitee.com/kooljun/helloworld.git
          git clone https://gitee.com/kooljun/passwall2.git

      - name: 更新 feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 生成配置
        run: |
          cd openwrt
          cat > .config << EOF
CONFIG_TARGET_ramips=y
CONFIG_TARGET_ramips_mt7621=y
CONFIG_TARGET_ramips_mt7621_DEVICE_xiaomi_mi-router-cr6606=y
CONFIG_PACKAGE_luci-app-ssr-plus=y
CONFIG_PACKAGE_luci-app-passwall2=y
CONFIG_PACKAGE_luci-app-frpc=y
EOF
          make defconfig

      - name: 下载依赖
        run: cd openwrt && make download -j8

      - name: 编译固件
        run: cd openwrt && make -j$(nproc) || make -j1 V=s

      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: cr6606-firmware
          path: openwrt/bin/targets/ramips/mt7621/*
